app:
  async:
    pull-request-opened-derived-metrics:
      core-pool-size: 4
      max-pool-size: 8
      queue-capacity: 100
      keep-alive-seconds: 60
      await-termination-seconds: 30
      wait-for-tasks-to-complete-on-shutdown: true
      thread-name-prefix: async-pr-metrics-
