token:
  access-key: thisIsA32ByteAccessTokenKeyForHS
  refresh-key: thisIsA32ByteRefreshTokenKeyForH
  encryption-key: thisIsA32ByteEncryptionKeyForAES
  issuer: local-issuer
  access-expired-seconds: 3600
  refresh-expired-seconds: 259200
  access-expired-millis-seconds: 3600000
  refresh-expired-millis-seconds: 259200000
